version: '3'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_DB: authenticat
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000  # Remove this line if you want to use the CMD from Dockerfile
    volumes:
      - .:/django_authentication  # Adjusted volume mount path to match Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: